'use client';

import { Pencil, Trash2 } from 'lucide-react';
import { deleteAlert } from '@/lib/actions/alert.actions';
import { toast } from 'sonner';

export default function AlertsList({ alerts, logos, onEdit, onDeleted }: { alerts: PriceAlert[]; logos: Record<string, string>; onEdit: (alert: PriceAlert) => void; onDeleted: () => void }) {
    const remove = async (id: string) => { const result = await deleteAlert(id); if (!result.success) return toast.error(result.error || 'Could not delete alert.'); toast.success('Alert deleted'); onDeleted(); };
    return <div className="alert-list scrollbar-hide-default">{alerts.length === 0 ? <div className="alert-empty">No alerts yet. Create one from a watchlist stock.</div> : alerts.map((alert) => <article key={alert.id} className="alert-item"><div className="alert-details"><div className="flex min-w-0 items-center gap-3"><div className="flex size-12 shrink-0 items-center justify-center overflow-hidden rounded-md bg-gray-600"><span role="img" aria-label={`${alert.company} logo`} className="size-full bg-contain bg-center bg-no-repeat" style={logos[alert.symbol] ? { backgroundImage: `url("${logos[alert.symbol]}")` } : undefined}>{!logos[alert.symbol] && <span className="flex size-full items-center justify-center font-bold text-yellow-400">{alert.symbol.slice(0, 2)}</span>}</span></div><div className="min-w-0"><p className="alert-company truncate">{alert.company}</p><p className="alert-price">{alert.symbol}</p></div></div><span className="font-medium text-gray-400">{alert.symbol}</span></div><p className="text-sm text-gray-500">{alert.alertName}</p><div className="alert-actions mt-1"><div><span className="alert-price">Price {alert.alertType === 'upper' ? '>' : '<'} ${alert.threshold.toFixed(2)}</span><span className="ml-2 rounded bg-yellow-500/20 px-2 py-1 text-xs text-yellow-400">Once per {alert.frequency}</span></div><div className="flex"><button onClick={() => onEdit(alert)} className="alert-update-btn p-2" aria-label="Edit alert"><Pencil className="size-4" /></button><button onClick={() => remove(alert.id)} className="alert-delete-btn p-2" aria-label="Delete alert"><Trash2 className="size-4" /></button></div></div></article>)}</div>;
}
